-- MySQL Script generated by MySQL Workbench
-- Tue Mar 29 16:55:22 2021
-- Model: AGILE EER Diagram

CREATE DATABASE agileDB
	DEFAULT CHARSET = utf8mb4
	DEFAULT ENCRYPTION = 'N';
    
-- -----------------------------------------------------
-- Schema agileDB
-- -----------------------------------------------------

USE agileDB;

-- ---------------------------------------------------------------
-- Table `Colaborador` - Entidade que realiza as suas tarefas
-- ---------------------------------------------------------------
CREATE TABLE Colaborador (
    IDcolab INT NOT NULL,
    Nome VARCHAR(45),
    Departamento VARCHAR(20),
    local_de_trabalho VARCHAR(20),
    anos_na_empresa INT,
		PRIMARY KEY (IDcolab)
)
	ENGINE = InnoDB;

-- --------------------------------------------------------------------------
-- Table `Revisor` - Entidade que avalia os commits dos contribuidores
-- --------------------------------------------------------------------------
CREATE TABLE Revisor (
    fk_Colaborador_IDcolab INT NOT NULL,
    fk_Colaborador_IDrevisor INT NOT NULL,
		PRIMARY KEY (fk_Colaborador_IDcolab),
		FOREIGN KEY ( fk_Colaborador_IDrevisor) REFERENCES Colaborador(IDcolab) 
);





